# .travis.yml - https://github.com/mloskot/mateusz.loskot.net
language: generic
dist: trusty
sudo: enabled

install:
  - sudo apt-get install -y lftp
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.24/hugo_0.24_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

deploy:
  provider: script
  script: chmod +x scripts/deploy.sh && scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
