# .travis.yml - https://github.com/mloskot/mateusz.loskot.net
dist: xenial
language: generic
sudo: enabled

install:
  - sudo apt-get install -y lftp
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

deploy:
  provider: script
  script: sh scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
