baseURL = "http://mateusz.loskot.net/"
languageCode = "en-us"
title = "Mateusz Loskot"

[params]
  description = "Mateusz Łoskot's personal website and blog"
  tagline = "hacking on, working out, living up"
  author = "mloskot"
  email = "mateusz@loskot.net"
  aboutme = "about.me/mloskot"
  cadcorp = "cadcorp.com"
  flickr = "flic.kr/mloskot"
  github = "github.com/mloskot"
  instagram = "instagr.am/mloskot"
  linkedin = "linkedin.com/in/mateuszloskot"
  ohloh = "ohloh.net/accounts/mloskot"
  osgeo = "osgeo.org"
  twitter = "twitter.com/mloskot"
  vimeo = "vimeo.com/mloskot"
  youtube = "youtube.com/mloskot"