baseURL = "http://mateusz.loskot.net/"
languageCode = "en-us"
title = "Mateusz Loskot"

[params]
  description = "Mateusz Łoskot's personal website and blog"
  tagline = "hacking on, working out, living up"
  email = "mateusz@loskot.net"
  aboutme = "about.me/mloskot"
  cadcorp = "https://cadcorp.com"
  flickr = "flic.kr/mloskot"
  github = "github.com/mloskot"
  gplus = "gplus.to/mloskot"
  linkedin = "linkedin.com/in/mateuszloskot"
  ohloh = "ohloh.net/accounts/mloskot"
  osgeo = "https://osgeo.org"
  twitter = "twitter.com/mloskot"
  vimeo = "vimeo.com/mloskot"
  youtube = "youtube.com/mloskot"